# Defining the stages order
stages:
  - test
  - release
  - next

# Excluding some branches
branches:
  except:
    - master

# Caching Maven repository
cache:
  directories:
    - $HOME/.m2

# Defining vars
env:
  global:
    - GIT_USER_MAIL="travis@travis-ci.org"
    - GIT_USER_NAME="Travis CI"
    - GIT_BRANCH_RELEASE="master"
    - GIT_BRANCH_DEVELOP="develop"

# Defining the jobs
jobs:
  include:

    # Tests
    - stage: test
      language: java
      install: skip
      script:
        - mvn clean test

    # Release to Maven Central
    - stage: release
      language: java
      if: (NOT type IN (pull_request)) AND (branch = release)
      install: skip
      before_script:
        - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import || exit
        - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust || exit
        - git config --global user.email "$GIT_USER_MAIL" || exit
        - git config --global user.name "$GIT_USER_NAME" || exit
        - git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* || exit
        - git fetch --all || exit
        - git checkout "$GIT_BRANCH_RELEASE" || exit
        - git merge --ff-only "$TRAVIS_COMMIT" || exit
      script:
        - mvn versions:set -DremoveSnapshot=true -DgenerateBackupPoms=false || exit
        - mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease || exit
        - mvn help:evaluate -N -Dexpression=project.version|grep -v '\[' || exit
        - export PROJECT_VERSION=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[') || exit
        - git add . || exit
        - git commit -m "[Travis CI] Release $PROJECT_VERSION" || exit
        - git tag -a "$PROJECT_VERSION" -m "Release $PROJECT_VERSION" || exit
        - git push https://${GITHUB_TOKEN}@github.com/egoettelmann/api-specs-comparator.git || exit

    # Next development iteration
    - stage: next
      language: java
      if: (NOT type IN (pull_request)) AND (branch = release)
      install: skip
      before_script:
        - git config --global user.email "$GIT_USER_MAIL" || exit
        - git config --global user.name "$GIT_USER_NAME" || exit
        - git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* || exit
        - git fetch --all || exit
        - git checkout "$GIT_BRANCH_DEVELOP" || exit
        - git merge --ff-only "$GIT_BRANCH_RELEASE" || exit
      script:
        - mvn versions:set -DnextSnapshot=true -DgenerateBackupPoms=false || exit
        - mvn help:evaluate -N -Dexpression=project.version|grep -v '\[' || exit
        - export PROJECT_VERSION=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[') || exit
        - git add . || exit
        - git commit -m "[Travis CI] Next development iteration $PROJECT_VERSION" || exit
        - git push https://${GITHUB_TOKEN}@github.com/egoettelmann/api-specs-comparator.git || exit
