version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  set-version:
    docker:
      - image: circleci/openjdk:8u242-stretch
    steps:
      - checkout
      - run: |
          mvn versions:set -DremoveSnapshot=true -DgenerateBackupPoms=false
          git status
          git config user.name "CircleCI"
          git config user.email "git@circleci.com"
          git add .
          git commit -m "Release version [skip ci]"
          git tag -a "v" -m "Release "
      - persist_to_workspace:
          root: ~/
          path: ./project/pom.xml
  build:
    docker:
      - image: circleci/openjdk:8u242-stretch
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: mvn clean install

workflows:
  build-and-deploy:
    jobs:
      - set-version:
          filters:
            branches:
              only: ci-tests
      - build:
          requires:
            - set-version
          filters:
            branches:
              only: ci-tests
