version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  set-version:
    docker:
      - image: circleci/openjdk:8u181-stretch
    steps:
      - checkout
      - run: mvn versions:set -DremoveSnapshot=true -DgenerateBackupPoms=false
  build:
    docker:
      - image: circleci/openjdk:8u181-stretch
    steps:
      - checkout
      - run: mvn clean install

workflows:
  build-deploy:
    jobs:
      - set-version:
          filters:
            branches:
              only: ci-tests
      - build:
          filters:
            branches:
              only: ci-tests
