version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  set-version:
    docker:
      - image: circleci/openjdk:8u242-stretch
    steps:
      - checkout
      - run: |
          mvn versions:set -DremoveSnapshot=true -DgenerateBackupPoms=false
          mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
          PROJECT_VERSION=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
          ls -al
          git config user.name "CircleCI"
          git config user.email "git@circleci.com"
          git add .
          git commit -m "Release version $PROJECT_VERSION [skip ci]"
          git tag -a "v$PROJECT_VERSION" -m "Release $PROJECT_VERSION"
      - persist_to_workspace:
          root: /root
          path: project
  build:
    docker:
      - image: circleci/openjdk:8u242-stretch
    steps:
      - attach_workspace:
          at: ~/
      - run: mvn clean install

workflows:
  build-and-deploy:
    jobs:
      - set-version:
          filters:
            branches:
              only: ci-tests
      - build:
          requires:
            - set-version
          filters:
            branches:
              only: ci-tests
